### Creates a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "fullName": "John Smith",
    "email": "john.smith4@example.com",
    "dateOfBirth": "2000-01-01",
    "address": "123 Main St",
    "dateOfRegistration": "2024-04-13"
}

###