services:
  patient-service-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_USER=admin_viewer'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5000:5432'
    networks:
      - internal

#  billing-service-db:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=db'
#      - 'POSTGRES_USER=admin_viewer'
#      - 'POSTGRES_PASSWORD=password'
#    ports:
#      - '5001:5432'
#    networks:
#      - internal

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - patient-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_viewer
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    networks:
      - internal

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
      - '9001:9001'
#    depends_on:
#      - billing-service-db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://billing-service-db:5432/db
#      SPRING_DATASOURCE_USERNAME: admin_viewer
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_SQL_INIT_MODE: always
    networks:
      - internal

networks:
  internal:
    driver: bridge