### Creates a new patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
    "fullName": "Jack Joneson",
    "email": "jack.joneson@me.com",
    "dateOfBirth": "2000-01-01",
    "address": "123 Main St, Anytown, USA",
    "dateOfRegistration": "2025-01-01"
}

###